# thejokers69/_config.yml
title: "Welcome to The Joker's Portfolio"
description: "My personal site and projects"
baseurl: ""
url: "https://thejokers69.tech"
theme: jekyll-theme-minimal

sass:
  sass_dir: assets/css
  style: compressed

plugins:
  - jekyll-seo-tag

collections:
  pages:
    output: true

cache:
  enabled: true
  duration: 3600 # 1 heure