# thejokers69/_config.yml
title: "Mohamed Lakssir | TheJokers69"
description: "Computer Engineering Student & Full-Stack Developer"
baseurl: ""
url: "https://thejokers69.tech"
theme: jekyll-theme-minimal

sass:
  sass_dir: assets/css
  style: compressed

plugins:
  - jekyll-seo-tag

collections:
  pages:
    output: true

cache:
  enabled: true
  duration: 3600