# thejokers69/_config.yml
title: "Welcome to The Joker's Portfolio"
description: "My personal site and projects"
baseurl: ""
url: "https://thejokers69.tech"
theme: jekyll-theme-minimal

sass:
  style: compressed