# thejokers69/_config.yml
title: "Mohamed Lakssir | TheJokers69"
description: "Computer Engineering Student & Full-Stack Developer"
baseurl: ""
url: "https://thejokers69.tech"

sass:
  sass_dir: assets/css
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true

cache:
  enabled: true
  duration: 3600
# Suppression de "theme: jekyll-theme-minimal" pour forcer l'utilisation de vos layouts personnalisés.