# thejokers69/_config.yml
title: "Mohamed Lakssir | TheJokers69"
description: "Computer Engineering Student & Full-Stack Developer"
baseurl: "/thejokers69"
url: "https://thejokers69.github.io"
# Using local layouts rather than a gem-based theme
theme: jekyll-theme-minimal

sass:
  sass_dir: assets/css
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true

cache:
  enabled: true
  duration: 3600